version: '3'
services:
  app:
    image: task3:university_web_application
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/foxminded_university
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: foxminded_university
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234